version: '3.8'
services:
  labo-ai:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    env_file:
      - .env

  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    env_file:
      - .env

  frontend:
      build:
        context: ./frontend
      ports:
        - "3000:3000"
      volumes:
        - ./frontend:/app
        - /app/node_modules
      depends_on:
        - backend 
      environment:
        - NEXT_PUBLIC_API_URL=http://localhost:8000